#!/bin/bash 
TOWER_GUID=a7ad
OSP_GUID=0f3c
OPENTLC_LOGIN=maciej.wawrzyniak-atos.net
OPENTLC_PASSWORD=8wawa888W
GITHUB_REPO=https://github.com/wawa8/ansible_advance_homework
JQ_REPO_BASE=http://www.opentlc.com/download/ansible_bootcamp
REGION=us-east-1
RH_MAIL_ID=maciej.wawrzyniak*
